import type { Metadata } from "next";
import { AuthProvider } from "@/lib/auth";
import Layout from "@/components/Layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "My Google AI Studio App",
  description: "Generated by AI Studio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          <Layout>
            {children}
          </Layout>
        </AuthProvider>
      </body>
    </html>
  );
}
